conditionsDict = {
    "000" : { "main" : "Missing", "description" : "missing",
              "colour": "red", "interval" : 3 },
    
    "200" : { "main" : "Thunderstorm", "description" : "thunderstorm with light rain",
              "colour": "purple", "interval" : 3 },
    "201" : { "main" : "Thunderstorm", "description" : "thunderstorm with rain",
              "colour": "purple", "interval" : 2 },
    "202" : { "main" : "Thunderstorm", "description" : "thunderstorm with heavy rain",
              "colour": "purple", "interval" : 1 },
    "210" : { "main" : "Thunderstorm", "description" : "light thunderstorm",
              "colour" : "purple", "interval" : 3 },
    "211" : { "main" : "Thunderstorm", "description" : "thunderstorm",
              "colour" : "purple", "interval" : 3 },
    "212" : { "main" : "Thunderstorm", "description" : "heavy thunderstorm",
              "colour" : "purple", "interval" : 3 },
    "221" : { "main" : "Thunderstorm", "description" : "ragged thunderstorm",
              "colour" : "purple", "interval" : 3 },
    "230" : { "main" : "Thunderstorm", "description" : "thunderstorm with light drizzle",
              "colour" : "purple", "interval" : 3 },
    "231" : { "main" : "Thunderstorm", "description" : "thunderstorm with drizzle",
              "colour" : "purple", "interval" : 3 },
    "232" : { "main" : "Thunderstorm", "description" : "thunderstorm with heavy drizzle",
              "colour" : "purple", "interval" : 2 },

    "300" : { "main" : "Drizzle", "description" : "light intensity drizzle",
              "colour" : "light blue", "interval" : 3 },
    "301" : { "main" : "Drizzle", "description" : "drizzle",
              "colour" : "blue", "interval" : 2 },
    "302" : { "main" : "Drizzle", "description" : "heavy intensity drizzle",
              "colour" : "blue", "interval" : 1 },
    "310" : { "main" : "Drizzle", "description" : "light intensity drizzle rain",
              "colour" : "light blue", "interval" : 3 },
    "311" : { "main" : "Drizzle", "description" : "drizzle rain",
              "colour" : "blue", "interval" : 2 },
    "312" : { "main" : "Drizzle", "description" : "heavy intensity drizzle rain",
              "colour" : "blue", "interval" : 1 },
    "313" : { "main" : "Drizzle", "description" : "shower rain and drizzle",
              "colour" : "blue", "interval" : 2 },
    "314" : { "main" : "Drizzle", "description" : "heavy shower rain and drizzle",
              "colour" : "blue", "interval" : 1 },
    "321" : { "main" : "Drizzle", "description" : "shower drizzle",
              "colour" : "blue", "interval" : 2 },

    "500" : { "main" : "Rain", "description" : "light rain",
              "colour" : "light blue", "interval" : 3 },
    "501" : { "main" : "Rain", "description" : "moderate rain",
              "colour" : "blue", "interval" : 2 },
    "502" : { "main" : "Rain", "description" : "heavy intensity rain",
              "colour" : "blue", "interval" : 1 },
    "503" : { "main" : "Rain", "description" : "very heavy rain",
              "colour" : "blue", "interval" : 1 },
    "504" : { "main" : "Rain", "description" : "extreme rain",
              "colour" : "blue", "interval" : 1 },
    "511" : { "main" : "Rain", "description" : "freezing rain",
              "colour" : "blue", "interval" : 1 },
    "520" : { "main" : "Rain", "description" : "light intensity shower rain",
              "colour" : "light blue", "interval" : 3 },
    "521" : { "main" : "Rain", "description" : "shower rain",
              "colour" : "blue", "interval" : 2 },
    "522" : { "main" : "Rain", "description" : "heavy intensity shower rain",
              "colour" : "blue", "interval" : 1 },
    "531" : { "main" : "Rain", "description" : "ragged shower rain",
              "colour" : "blue", "interval" : 2 },

    "600" : { "main" : "Snow", "description" : "light snow",
              "colour" : "white", "interval" : 3 },
    "601" : { "main" : "Snow", "description" : "snow",
              "colour" : "white", "interval" : 2 },
    "602" : { "main" : "Snow", "description" : "heavy snow",
              "colour" : "white", "interval" : 1 },
    "611" : { "main" : "Snow", "description" : "sleet",
              "colour" : "blue", "interval" : 1 },
    "612" : { "main" : "Snow", "description" : "shower sleet",
              "colour" : "blue", "interval" : 2 },
    "615" : { "main" : "Snow", "description" : "light rain and snow",
              "colour" : "light blue", "interval" : 3 },
    "616" : { "main" : "Snow", "description" : "rain and snow",
              "colour" : "blue", "interval" : 2 },
    "620" : { "main" : "Snow", "description" : "light shower snow",
              "colour" : "white", "interval" : 3 },
    "621" : { "main" : "Snow", "description" : "shower snow",
              "colour" : "white", "interval" : 2 },
    "622" : { "main" : "Snow", "description" : "heavy shower snow",
              "colour" : "white", "interval" : 1 },

    "701" : { "main" : "Atmosphere", "description" : "mist",
              "colour" : "green", "interval" : 0 },
    "711" : { "main" : "Atmosphere", "description" : "smoke",
              "colour" : "green", "interval" : 0 },
    "721" : { "main" : "Atmosphere", "description" : "haze",
              "colour" : "green", "interval" : 0 },
    "731" : { "main" : "Atmosphere", "description" : "sand, dust whirls",
              "colour" : "green", "interval" : 0 },
    "741" : { "main" : "Atmosphere", "description" : "fog",
              "colour" : "green", "interval" : 0 },
    "751" : { "main" : "Atmosphere", "description" : "sand",
              "colour" : "green", "interval" : 0 },
    "761" : { "main" : "Atmosphere", "description" : "dust",
              "colour" : "green", "interval" : 0 },
    "762" : { "main" : "Atmosphere", "description" : "volcanic ash",
              "colour" : "green", "interval" : 0 },
    "771" : { "main" : "Atmosphere", "description" : "squalls",
              "colour" : "green", "interval" : 0 },
    "781" : { "main" : "Atmosphere", "description" : "tornado",
              "colour" : "purple", "interval" : 0 },

    "800" : { "main" : "Clear", "description" : "clear sky",
              "colour" : "gold", "interval" : 0 },

    "801" : { "main" : "Clouds", "description" : "few clouds",
              "colour" : "gold", "interval" : 0 },
    "802" : { "main" : "Clouds", "description" : "scattered clouds",
              "colour" : "white", "interval" : 0 },
    "803" : { "main" : "Clouds", "description" : "broken clouds",
              "colour" : "white", "interval" : 0 },
    "804" : { "main" : "Clouds", "description" : "overcast clouds",
              "colour" : "white", "interval" : 0 },

    "900" : { "main" : "Extreme", "description" : "tornado",
              "colour" : "purple", "interval" : 0 },
    "901" : { "main" : "Extreme", "description" : "tropical storm",
              "colour" : "purple", "interval" : 0 },
    "902" : { "main" : "Extreme", "description" : "hurricane",
              "colour" : "red", "interval" : 0 },
    "903" : { "main" : "Extreme", "description" : "cold",
              "colour" : "blue", "interval" : 0 },
    "904" : { "main" : "Extreme", "description" : "hot",
              "colour" : "orange", "interval" : 0 },
    "905" : { "main" : "Extreme", "description" : "windy",
              "colour" : "red", "interval" : 0 },
    "906" : { "main" : "Extreme", "description" : "hail",
              "colour" : "blue", "interval" : 2 },

    "951" : { "main" : "Additional", "description" : "calm",
              "colour" : "white", "interval" : 0 },
    "952" : { "main" : "Additional", "description" : "light breeze",
              "colour" : "white", "interval" : 0 },
    "953" : { "main" : "Additional", "description" : "gentle breeze",
              "colour" : "white", "interval" : 0 },
    "954" : { "main" : "Additional", "description" : "moderate breeze",
              "colour" : "white", "interval" : 0 },
    "955" : { "main" : "Additional", "description" : "fresh breeze",
              "colour" : "white", "interval" : 0 },
    "956" : { "main" : "Additional", "description" : "strong breeze",
              "colour" : "red", "interval" : 0 },
    "957" : { "main" : "Additional", "description" : "high wind, near gale",
              "colour" : "red", "interval" : 0 },
    "958" : { "main" : "Additional", "description" : "gale",
              "colour" : "red", "interval" : 0 },
    "959" : { "main" : "Additional", "description" : "severe gale",
              "colour" : "red", "interval" : 0 },
    "960" : { "main" : "Additional", "description" : "storm",
              "colour" : "purple", "interval" : 0 },
    "961" : { "main" : "Additional", "description" : "violent storm",
              "colour" : "red", "interval" : 0 },
    "962" : { "main" : "Additional", "description" : "hurricane",
              "colour" : "red", "interval" : 0 }
}

# starting/showcase weather conditions
conditionsShowcase = {
    'weather' : '902',
    'forecast' : [ '904', '800', '701', '300', '301', '202', '804' ]
}

# RGB colour defitions
colourDict =   {
    'red' :         { 'r' : 255,    'g' : 0,    'b' : 0     },
    'orange' :      { 'r' : 255,    'g' : 50,   'b' : 0     },
    'gold' :        { 'r' : 200,    'g' : 100,  'b' : 0     },
    'green' :       { 'r' : 0,      'g' : 125,  'b' : 0     },
    'light blue' :  { 'r' : 25,     'g' : 25,   'b' : 200   },
    'blue' :        { 'r' : 0,      'g' : 0,    'b' : 100   },
    'purple' :      { 'r' : 125,    'g' : 0,    'b' : 125   },
    'white' :       { 'r' : 200,    'g' : 200,  'b' : 200   }
}
